# Generated by Django 5.0 on 2024-01-31 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamers',
            fields=[
                ('customusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gamer_tag', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customusers',),
        ),
    ]
